### PR TITLE
update package to 2017

### PR DESCRIPTION
**Pull request by justinwoo**
surprisingly few changes, changed the address spec to use EOL

### CODE REVIEW

**Comment by justinwoo** [comment]
might be good to have a .travis.yml config like https://github.com/justinwoo/purescript-bundaegi/blob/master/.travis.yml

**Comment by cdepillabout** [comment]
Thanks for this PR.  Looks good.

I just added you as a contributor for this repository.  I believe you should get an email about it.  Feel free to do a release and push docs to pursuit.

Also, feel free to make changes in the future without sending sending a PR first.  Of course, if you want another set of eyes checking some changes, I'm completely fine with reviewing any code.

**Comment by cdepillabout** [comment]
I haven't really been keeping this repo up to date, so I really appreciate that you took the time to do this :+1:

**Comment by justinwoo** [comment]
np! Someone was asking about on Slack and I figured updating wouldn't be too much work

**Pull request merged**
